'use strict';
const inboxPanel=uiNode('section','workspace-card');inboxPanel.id='meta-inbox';inboxPanel.hidden=true;$('#workspace').append(inboxPanel);
const inboxHeader=uiNode('div','inbox-toolbar'),channelLabel=uiNode('label','','Channel'),channelFilter=uiNode('select');channelFilter.id='inbox-channel';for(const [v,n] of [['facebook','Facebook'],['instagram','Instagram'],['whatsapp','WhatsApp']])channelFilter.append(new Option(n,v));channelLabel.append(channelFilter);const inboxRefresh=uiNode('button','','Refresh inbox'),inboxSync=uiNode('button','','Sync recent conversations'),inboxMore=uiNode('button','','Sync next page');inboxMore.hidden=true;inboxHeader.append(channelLabel,inboxRefresh,inboxSync,inboxMore);inboxPanel.append(inboxHeader);
const inboxStatus=uiNode('p','hint');inboxStatus.setAttribute('role','status');inboxPanel.append(inboxStatus);const layout=uiNode('div','inbox-layout'),threadList=uiNode('div','inbox-list'),threadView=uiNode('div','inbox-thread');layout.append(threadList,threadView);inboxPanel.append(layout);
let inboxThreads=[],activeThread=null,syncCursor=null,replyAttempt=null;
inboxNav.addEventListener('click',()=>{ $('#wa-broadcast-panel').hidden=true;$('#pipeline-panel').hidden=true;inboxPanel.hidden=false;loadInbox();});
for(const b of [$('#pipeline-tab'),followNav,$('#wa-broadcast-tab')])b.addEventListener('click',()=>{inboxPanel.hidden=true;});
channelFilter.addEventListener('change',()=>{syncCursor=null;inboxMore.hidden=true;loadInbox();});inboxRefresh.addEventListener('click',loadInbox);
async function loadInbox(){threadList.replaceChildren();threadView.replaceChildren(uiNode('p','hint','Choose a conversation to view its messages.'));activeThread=null;
 if(channelFilter.value==='whatsapp'){inboxStatus.textContent='WhatsApp uses the existing Cloud API inbox. Enquiries remain on 7997994493; API replies use 7997994495.';const open=uiNode('button','','Open WhatsApp replies & delivery');open.addEventListener('click',()=>{inboxPanel.hidden=true;switchCrmTab(true);activeNav(inboxNav,'Conversations');showBroadcastSection('conversations');});threadView.replaceChildren(open);return;}
 if(demo){inboxThreads=[{id:'sample-thread',channel:channelFilter.value,participant_name:'Sample visitor',participant_id:'Fictional account',latest_at:new Date().toISOString()}];inboxStatus.textContent='Sample inbox · no Meta connection or sends.';renderInboxThreads();return;}
 inboxStatus.textContent='Checking connection…';try{const state=await request('/functions/v1/meta-conversations',{method:'POST',body:JSON.stringify({action:'status'})});inboxStatus.textContent=state[channelFilter.value]?'Credentials configured. Sync checks whether Meta grants conversation access.':'Connection pending: Page/account IDs and Page token need setup in Supabase.';inboxThreads=await request('/rest/v1/meta_threads?select=*&channel=eq.'+channelFilter.value+'&order=latest_at.desc.nullslast&limit=100');renderInboxThreads();}catch(e){inboxStatus.textContent=e.message;}}
function renderInboxThreads(){if(!inboxThreads.length){threadList.append(uiNode('p','hint','No conversations stored yet. Connect Meta, then sync or receive a new message.'));return;}for(const t of inboxThreads){const b=uiNode('button','thread-item',t.participant_name||t.participant_id);b.append(uiNode('small','',t.channel+' · '+(t.latest_at?indiaTime(t.latest_at):'No messages')));b.addEventListener('click',()=>openInboxThread(t));threadList.append(b);}}
async function openInboxThread(t){activeThread=t;replyAttempt=null;threadView.replaceChildren(uiNode('h3','',t.participant_name||t.participant_id));try{const messages=demo?[{direction:'incoming',body:'Hello, I would like to know more about the NIA visitor event.',event_at:new Date().toISOString()}]:await request('/rest/v1/meta_messages?thread_id=eq.'+t.id+'&select=*&order=event_at.desc&limit=100');const history=uiNode('div','inbox-history');for(const m of [...messages].reverse()){const box=uiNode('article','inbox-message '+m.direction);box.append(uiNode('p','',m.body),uiNode('small','',indiaTime(m.event_at)));history.append(box);}threadView.append(history);
 const linkForm=uiNode('form','inbox-link'),leadLabel=uiNode('label','','Link to visitor lead'),leadSelect=uiNode('select');leadSelect.append(new Option('Not linked',''));for(const l of leads)leadSelect.append(new Option(l.name+' · '+l.company,l.id));leadSelect.value=t.lead_id||'';leadLabel.append(leadSelect);const linkButton=uiNode('button','','Save lead link');linkButton.disabled=demo;linkForm.append(leadLabel,linkButton);linkForm.addEventListener('submit',async e=>{e.preventDefault();linkButton.disabled=true;try{await request('/rest/v1/rpc/meta_link_lead',{method:'POST',body:JSON.stringify({p_thread:t.id,p_lead:leadSelect.value||null})});t.lead_id=leadSelect.value;inboxStatus.textContent='Conversation linked to lead.';}catch(err){inboxStatus.textContent=err.message;}finally{linkButton.disabled=demo;}});threadView.append(linkForm);
 const last=messages.filter(m=>m.direction==='incoming').sort((a,b)=>Date.parse(b.event_at)-Date.parse(a.event_at))[0],age=Date.now()-Date.parse(last?.event_at),canReply=!demo&&Number.isFinite(age)&&age>=0&&age<86400000;
 const form=uiNode('form','inbox-reply'),label=uiNode('label','','Reply'),body=uiNode('textarea');body.required=true;body.maxLength=1000;body.rows=3;label.append(body);const send=uiNode('button','primary','Send '+t.channel+' reply');send.disabled=!canReply;form.append(label,send,uiNode('p','hint',demo?'Sample mode cannot send messages.':canReply?'Standard reply window is open.':'Reply window closed. Wait for a new customer message.'));form.addEventListener('submit',async e=>{e.preventDefault();if(!canReply)return;if(!replyAttempt||replyAttempt.body!==body.value||replyAttempt.thread_id!==t.id)replyAttempt={request_id:crypto.randomUUID(),thread_id:t.id,body:body.value};send.disabled=true;try{const result=await request('/functions/v1/meta-conversations',{method:'POST',body:JSON.stringify({action:'reply',...replyAttempt})});inboxStatus.textContent='Reply state: '+result.state+'. Accepted is not a delivery receipt.';if(result.state==='accepted')await openInboxThread(t);}catch(err){inboxStatus.textContent=err.message;}});threadView.append(form);
 }catch(e){inboxStatus.textContent=e.message;}}
async function syncInbox(next=false){if(demo)return;if(channelFilter.value==='whatsapp')return;inboxSync.disabled=inboxMore.disabled=true;try{const result=await request('/functions/v1/meta-conversations',{method:'POST',body:JSON.stringify({action:'sync',channel:channelFilter.value,...(next&&syncCursor?{after:syncCursor}:{})})});syncCursor=result.after;inboxMore.hidden=!syncCursor;await loadInbox();inboxStatus.textContent=result.count+' recent messages processed. Older history may be unavailable.';}catch(e){inboxStatus.textContent=e.message;}finally{inboxSync.disabled=inboxMore.disabled=false;}}
inboxSync.addEventListener('click',()=>syncInbox());inboxMore.addEventListener('click',()=>syncInbox(true));
