'use strict';
// Supabase owns OAuth/PKCE, refresh rotation and OTP verification. No provider secrets here.
const authKey='nia-crm-'+new URL(config.supabaseUrl).hostname;
const preferenceKey=authKey+'-remember';
const authStore=k=>k.endsWith('-code-verifier')||localStorage.getItem(preferenceKey)==='true'?localStorage:sessionStorage;
const sessionStorageAdapter={getItem:k=>authStore(k).getItem(k),setItem:(k,v)=>authStore(k).setItem(k,v),removeItem:k=>{localStorage.removeItem(k);sessionStorage.removeItem(k);}};
window.niaAuth=window.supabase.createClient(config.supabaseUrl,config.publishableKey,{auth:{storage:sessionStorageAdapter,storageKey:authKey,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}});
let loginEmail='',authGeneration=0;
$('#remember-login').checked=localStorage.getItem(preferenceKey)==='true';
function setLoginPersistence(){const remember=$('#remember-login').checked;sessionStorageAdapter.removeItem(authKey);localStorage.setItem(preferenceKey,String(remember));}
async function admitSession(session){const generation=++authGeneration;if(!session){token=null;if(!demo){$('#workspace').hidden=true;$('#login').hidden=false;$('#signout').hidden=true;}return;}token=session.access_token;try{const staff=await request('/rest/v1/crm_staff?select=user_id');if(generation!==authGeneration)return;if(!staff.length){await window.niaAuth.auth.signOut({scope:'local'});status('This account is not authorised for the NIA CRM.');return;}demo=false;await load();}catch(e){status(e.message);}}
window.niaAuth.auth.onAuthStateChange((event,session)=>{token=session?.access_token||null;if(event==='INITIAL_SESSION'||event==='SIGNED_IN'||event==='SIGNED_OUT')setTimeout(()=>admitSession(session),0);});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();loginEmail=new FormData(e.currentTarget).get('email').trim();setLoginPersistence();const button=e.currentTarget.querySelector('button');button.disabled=true;try{const {error}=await window.niaAuth.auth.signInWithOtp({email:loginEmail,options:{shouldCreateUser:false,emailRedirectTo:new URL('crm.html',location.href).href}});if(error)throw error;status('Open the newest sign-in link in your staff email. Your session will now survive refreshes.');}catch(e){status(e.message);}finally{button.disabled=false;}});
$('#otp-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{const {data,error}=await window.niaAuth.auth.verifyOtp({email:loginEmail,token:new FormData(e.currentTarget).get('code').trim(),type:'email'});if(error)throw error;e.currentTarget.reset();$('#otp-form').hidden=true;token=data.session?.access_token||null;}catch(e){status(e.message);}finally{button.disabled=false;}});
$('#change-email').addEventListener('click',()=>{$('#otp-form').hidden=true;$('#otp-form').reset();$('#login-form input[name=email]').focus();});
$('#google-login').addEventListener('click',async()=>{setLoginPersistence();const {error}=await window.niaAuth.auth.signInWithOAuth({provider:'google',options:{redirectTo:new URL('crm.html',location.href).href,queryParams:{prompt:'select_account'}}});if(error)status(error.message);});
$('#signout').addEventListener('click',async()=>{++authGeneration;token=null;demo=false;leads=[];selectedTemplate=null;selectedContacts.clear();for(const id of ['rows','wa-events','wa-campaigns','wa-contact-rows','wa-template-rows'])$('#'+id)?.replaceChildren();threadList.replaceChildren();threadView.replaceChildren();inboxThreads=[];activeThread=null;$('#workspace').hidden=true;$('#login').hidden=false;$('#signout').hidden=true;$('#mode').textContent='Staff sign-in';const {error}=await window.niaAuth.auth.signOut();sessionStorageAdapter.removeItem(authKey);status(error?'Signed out on this device. Server logout could not be confirmed.':'Signed out.');});
(async()=>{try{const r=await fetch(config.supabaseUrl+'/auth/v1/settings',{headers:{apikey:config.publishableKey}});const settings=await r.json();const enabled=r.ok&&settings.external?.google===true;$('#google-login').disabled=!enabled;$('#google-login-status').textContent=enabled?'Use your approved Google account.':'Google sign-in setup is pending. Use email-link login until it is enabled.';}catch{$('#google-login-status').textContent='Could not check Google login. Use email-link login.';}})();
