'use strict';
const stages=['New enquiry','Contacted','Qualified','Paid visitor','Attended','Membership discussion','Joined','Not proceeding'];
const $=s=>document.querySelector(s);let leads=[],token=null,demo=false,editing=null;
const config=window.NIA_CONFIG||{};const configured=Boolean(config.supabaseUrl&&config.publishableKey);
for(const s of stages)for(const target of ['#stage-filter','[name=stage]']){const o=document.createElement('option');o.value=o.textContent=s;$(target).append(o)}
function status(message){$('#status').textContent=message}
async function request(path,options={}){const response=await fetch(config.supabaseUrl+path,{...options,headers:{apikey:config.publishableKey,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...options.headers}});const text=await response.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('Unexpected server response. Please retry.')}if(!response.ok){if(response.status===401){token=null;$('#workspace').hidden=true;$('#login').hidden=false;}throw Error(data?.msg||data?.message||data?.error_description||'Request failed.')}return data}
function cell(row,text){const td=document.createElement('td');td.textContent=text??'—';row.append(td);return td}
function render(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});const metrics=[['Total leads',leads.length],['Paid visitors',leads.filter(l=>l.payment_status==='paid').length],['Follow-ups due',leads.filter(l=>l.follow_up&&l.follow_up<=today&&!['Joined','Not proceeding'].includes(l.stage)).length],['Attended',leads.filter(l=>['Attended','Membership discussion','Joined'].includes(l.stage)).length]];$('#metrics').replaceChildren();for(const [label,value] of metrics){const box=document.createElement('div');box.className='metric';const b=document.createElement('strong');b.textContent=value;const s=document.createElement('span');s.textContent=label;box.append(b,s);$('#metrics').append(box)}const query=$('#search').value.toLowerCase(),stage=$('#stage-filter').value;const filtered=leads.filter(l=>(!stage||l.stage===stage)&&[l.name,l.company,l.category,l.phone].some(v=>(v||'').toLowerCase().includes(query)));$('#rows').replaceChildren();for(const lead of filtered){const row=document.createElement('tr'),td=cell(row,'');const b=document.createElement('strong');b.textContent=lead.name;const small=document.createElement('small');small.textContent=lead.company;td.append(b,small);cell(row,lead.category);cell(row,lead.stage).className='tag-cell';cell(row,lead.payment_status);const due=cell(row,lead.follow_up);if(lead.follow_up&&lead.follow_up<today)due.className='overdue';cell(row,lead.owner);const action=cell(row,'');const button=document.createElement('button');button.textContent='Open';button.addEventListener('click',()=>edit(lead));action.append(button);$('#rows').append(row)}$('#empty').hidden=filtered.length>0}
function openWorkspace(){ $('#login').hidden=true;$('#workspace').hidden=false;$('#signout').hidden=false;$('#mode').textContent=demo?'Sample mode · Not saved':'Staff workspace';render()}
async function load(){if(demo){render();return}status('Loading lead records…');try{leads=await request('/rest/v1/leads?select=*&order=created_at.desc');openWorkspace();status('Lead records loaded. Payment status reflects verified backend records.')}catch(e){status(e.message)}}
let loginEmail='';
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();if(!configured){status('Supabase setup is pending. Staff login is not enabled yet.');return}loginEmail=new FormData(event.currentTarget).get('email').trim();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await request('/auth/v1/otp',{method:'POST',body:JSON.stringify({email:loginEmail,create_user:false})});$('#verify-form').hidden=false;status('Check your staff email for a sign-in code. Only authorised staff can access leads.')}catch(e){status(e.message)}finally{button.disabled=false}});
$('#verify-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const result=await request('/auth/v1/verify',{method:'POST',body:JSON.stringify({email:loginEmail,token:new FormData(event.currentTarget).get('code').trim(),type:'email'})});token=result.access_token;const staff=await request('/rest/v1/crm_staff?select=user_id');if(!staff.length){token=null;throw Error('This account is not authorised for the NIA CRM.')}demo=false;event.currentTarget.reset();$('#verify-form').hidden=true;await load()}catch(e){status(e.message)}finally{button.disabled=false}});
$('#demo').addEventListener('click',()=>{demo=true;token=null;leads=[{id:'sample-1',name:'Sample Visitor One',company:'Example Design Studio',category:'Architecture',phone:'',email:'',stage:'New enquiry',payment_status:'unpaid',source:'Meta campaign',notes:'Fictional sample. Interested in meeting business owners.',owner:'',follow_up:''},{id:'sample-2',name:'Sample Visitor Two',company:'Example IT Services',category:'IT services',phone:'',email:'',stage:'Paid visitor',payment_status:'paid',source:'Referral',notes:'Fictional sample showing a verified payment status.',owner:'Sample team',follow_up:''}];status('Sample mode: fictional records only. Changes disappear when you leave or reload. Real visitor details must wait for secure setup.');openWorkspace()});
$('#signout').addEventListener('click',async()=>{if(token)try{await request('/auth/v1/logout',{method:'POST'})}catch{}token=null;demo=false;leads=[];$('#workspace').hidden=true;$('#login').hidden=false;$('#signout').hidden=true;$('#mode').textContent=configured?'Staff sign-in':'Setup pending';status('Signed out.');});
function edit(lead){editing=lead?.id||null;const form=$('#edit-form');form.reset();$('#edit-status').textContent='';$('#editor-title').textContent=editing?'Lead details':'Add a lead';for(const key of ['name','phone','company','category','email','stage','owner','follow_up','source','notes','payment_status'])form.elements[key].value=lead?.[key]||({'stage':stages[0],source:'Manual',payment_status:'unpaid'}[key]||'');const phone=(lead?.phone||'').replace(/\D/g,'');$('#whatsapp').hidden=demo||!phone;$('#whatsapp').href='https://wa.me/'+(phone.length===10?'91'+phone:phone);$('#editor').showModal()}
$('#add').addEventListener('click',()=>edit(null));$('#close').addEventListener('click',()=>$('#editor').close());$('#search').addEventListener('input',render);$('#stage-filter').addEventListener('change',render);$('#refresh').addEventListener('click',load);
$('#edit-form').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);const value=Object.fromEntries(['name','phone','company','category','email','stage','owner','source','notes'].map(k=>[k,f.get(k).trim()]));value.follow_up=f.get('follow_up')||null;const button=event.currentTarget.querySelector('button.primary');button.disabled=true;try{if(demo){if(editing)leads=leads.map(l=>l.id===editing?{...l,...value}:l);else leads.unshift({...value,id:crypto.randomUUID(),payment_status:'unpaid'});render()}else{await request('/rest/v1/leads'+(editing?'?id=eq.'+encodeURIComponent(editing):''),{method:editing?'PATCH':'POST',body:JSON.stringify(value),headers:{Prefer:'return=minimal'}});await load()}$('#editor').close()}catch(e){$('#edit-status').textContent=e.message}finally{button.disabled=false}});
