'use strict';
const stages=['New enquiry','Contacted','Qualified','Paid visitor','Attended','Membership discussion','Joined','Not proceeding'];
const $=s=>document.querySelector(s);let leads=[],token=null,demo=false,editing=null;let activityRecords=[];
const config=window.NIA_CONFIG||{};const configured=Boolean(config.supabaseUrl&&config.publishableKey);
for(const s of stages)for(const target of ['#stage-filter','[name=stage]']){const o=document.createElement('option');o.value=o.textContent=s;$(target).append(o)}
function status(message){$('#status').textContent=message}
async function request(path,options={}){const response=await fetch(config.supabaseUrl+path,{...options,headers:{apikey:config.publishableKey,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...options.headers}});const text=await response.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('Unexpected server response. Please retry.')}if(!response.ok){if(response.status===401){token=null;$('#workspace').hidden=true;$('#login').hidden=false;}throw Error(data?.msg||data?.message||data?.error_description||'Request failed.')}return data}
function cell(row,text){const td=document.createElement('td');td.textContent=text??'—';row.append(td);return td}
function render(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});const metrics=[['Total leads',leads.length],['Paid visitors',leads.filter(l=>l.payment_status==='paid').length],['Follow-ups due',leads.filter(l=>l.follow_up&&l.follow_up<=today&&!['Joined','Not proceeding'].includes(l.stage)).length],['Attended',leads.filter(l=>['Attended','Membership discussion','Joined'].includes(l.stage)).length]];$('#metrics').replaceChildren();for(const [label,value] of metrics){const box=document.createElement('div');box.className='metric';const b=document.createElement('strong');b.textContent=value;const s=document.createElement('span');s.textContent=label;box.append(b,s);$('#metrics').append(box)}renderCampaignStats();const query=$('#search').value.toLowerCase(),stage=$('#stage-filter').value;const filtered=leads.filter(l=>queueMatches(l)&&(!stage||l.stage===stage)&&[l.name,l.company,l.category,l.phone].some(v=>(v||'').toLowerCase().includes(query)));$('#rows').replaceChildren();for(const lead of filtered){const row=document.createElement('tr'),td=cell(row,'');const b=document.createElement('strong');b.textContent=lead.name;const small=document.createElement('small');small.textContent=lead.company;td.append(b,small);cell(row,lead.category);cell(row,lead.stage).className='tag-cell';cell(row,lead.payment_status);const due=cell(row,lead.next_follow_up_at?indiaTime(lead.next_follow_up_at):lead.follow_up);if(lead.follow_up&&lead.follow_up<today)due.className='overdue';cell(row,lead.owner);const action=cell(row,'');const button=document.createElement('button');button.textContent='Open';button.addEventListener('click',()=>edit(lead));action.append(button);$('#rows').append(row)}$('#empty').hidden=filtered.length>0}
function openWorkspace(){ $('#login').hidden=true;$('#workspace').hidden=false;$('#signout').hidden=false;$('#mode').textContent=demo?'Sample mode · Not saved':'Staff workspace';render()}
async function load(){if(demo){render();return}status('Loading lead records…');try{leads=await request('/rest/v1/leads?select=*&order=created_at.desc');openWorkspace();status('Lead records loaded. Payment status reflects verified backend records.')}catch(e){status(e.message)}}
let loginEmail='';
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();if(!configured){status('Supabase setup is pending. Staff login is not enabled yet.');return}loginEmail=new FormData(event.currentTarget).get('email').trim();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await request('/auth/v1/otp?redirect_to='+encodeURIComponent(new URL('crm.html',location.href).href),{method:'POST',body:JSON.stringify({email:loginEmail,create_user:false})});status('Check your staff email and open the sign-in link. Only authorised staff can access leads.')}catch(e){status(e.message)}finally{button.disabled=false}});
$('#demo').addEventListener('click',()=>{demo=true;token=null;leads=[{id:'sample-1',name:'Sample Visitor One',company:'Example Design Studio',category:'Architecture',phone:'',email:'',stage:'New enquiry',payment_status:'unpaid',source:'Meta campaign',notes:'Fictional sample. Interested in meeting business owners.',owner:'',follow_up:''},{id:'sample-2',name:'Sample Visitor Two',company:'Example IT Services',category:'IT services',phone:'',email:'',stage:'Paid visitor',payment_status:'paid',source:'Referral',notes:'Fictional sample showing a verified payment status.',owner:'Sample team',follow_up:''}];status('Sample mode: fictional records only. Changes disappear when you leave or reload. Real visitor details must wait for secure setup.');openWorkspace()});
$('#signout').addEventListener('click',async()=>{if(token)try{await request('/auth/v1/logout',{method:'POST'})}catch{}token=null;demo=false;leads=[];$('#workspace').hidden=true;$('#login').hidden=false;$('#signout').hidden=true;$('#mode').textContent=configured?'Staff sign-in':'Setup pending';status('Signed out.');});
function edit(lead){editing=lead?.id||null;const form=$('#edit-form');form.reset();$('#edit-status').textContent='';$('#editor-title').textContent=editing?'Lead details':'Add a lead';for(const key of ['name','phone','company','category','email','stage','owner','next_follow_up_at','next_action','source','notes','payment_status'])form.elements[key].value=(key==='next_follow_up_at'?localTime(lead?.next_follow_up_at):lead?.[key])||({'stage':stages[0],source:'Manual',next_action:'Call',payment_status:'unpaid'}[key]||'');const phone=(lead?.phone||'').replace(/\D/g,'');$('#whatsapp').hidden=demo||!phone;$('#whatsapp').href='https://wa.me/'+(phone.length===10?'91'+phone:phone);$('#activity-section').hidden=!editing;$('#activity-status').textContent='';$('#activity-form').reset();$('#lead-context').textContent=lead?.attribution?.years_in_business?lead.attribution.years_in_business+' years in business · Campaign: '+(lead.attribution.utm_campaign||'direct'):'';$('#editor').showModal();if(editing)loadActivities(editing)}
$('#add').addEventListener('click',()=>edit(null));$('#close').addEventListener('click',()=>$('#editor').close());$('#search').addEventListener('input',render);$('#stage-filter').addEventListener('change',render);$('#refresh').addEventListener('click',load);
$('#edit-form').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);const value=Object.fromEntries(['name','phone','company','category','email','stage','owner','source','notes','next_action'].map(k=>[k,f.get(k).trim()]));value.next_follow_up_at=f.get('next_follow_up_at')?new Date(f.get('next_follow_up_at')+'+05:30').toISOString():null;value.follow_up=value.next_follow_up_at?localTime(value.next_follow_up_at).slice(0,10):null;const button=event.currentTarget.querySelector('button.primary');button.disabled=true;try{if(demo){if(editing)leads=leads.map(l=>l.id===editing?{...l,...value}:l);else leads.unshift({...value,id:crypto.randomUUID(),payment_status:'unpaid'});render()}else{await request('/rest/v1/leads'+(editing?'?id=eq.'+encodeURIComponent(editing):''),{method:editing?'PATCH':'POST',body:JSON.stringify(value),headers:{Prefer:'return=minimal'}});await load()}$('#editor').close()}catch(e){$('#edit-status').textContent=e.message}finally{button.disabled=false}});

(async()=>{const hash=new URLSearchParams(location.hash.slice(1));const incoming=hash.get('access_token');if(!incoming)return;history.replaceState(null,'',location.pathname+location.search);token=incoming;try{const staff=await request('/rest/v1/crm_staff?select=user_id');if(!staff.length){token=null;throw Error('This account is not authorised for the NIA CRM.')}demo=false;await load()}catch(e){token=null;status(e.message)}})();

if(configured){$('#mode').textContent='Staff sign-in';status('Sign in with your authorised staff email to access visitor records.')}

function indiaTime(value){return new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST'}
function localTime(value){if(!value)return '';return new Date(new Date(value).getTime()+19800000).toISOString().slice(0,16)}
function queueMatches(l){const queue=$('#queue-filter').value;if(!queue)return true;if(['Joined','Not proceeding'].includes(l.stage))return false;const next=l.next_follow_up_at;const today=localTime(new Date().toISOString()).slice(0,10);const date=next?localTime(next).slice(0,10):l.follow_up;if(queue==='unscheduled')return !date;if(!date)return false;if(queue==='today')return date===today;if(queue==='overdue')return date<today||(next&&new Date(next)<new Date());return date>today}
$('#queue-filter').addEventListener('change',render);
function renderActivities(){const list=$('#activity-list');list.replaceChildren();if(!activityRecords.length){list.textContent='No conversations logged yet.';return}for(const a of activityRecords){const box=document.createElement('article');box.className='activity';const title=document.createElement('strong');title.textContent=a.activity_type+' · '+a.outcome;const time=document.createElement('small');time.textContent=indiaTime(a.created_at);const note=document.createElement('p');note.textContent=a.note;box.append(title,time,note);list.append(box)}}
async function loadActivities(id){$('#activity-list').textContent='Loading conversation history…';try{activityRecords=demo?demoActivities.filter(a=>a.lead_id===id):await request('/rest/v1/lead_activities?select=*&lead_id=eq.'+encodeURIComponent(id)+'&order=created_at.desc');if(editing===id)renderActivities()}catch(e){$('#activity-list').textContent=e.message}}
let demoActivities=[];
$('#activity-form').addEventListener('submit',async event=>{event.preventDefault();const id=editing;if(!id)return;const f=new FormData(event.currentTarget),leadForm=$('#edit-form');const next=leadForm.elements.next_follow_up_at.value;const stage=leadForm.elements.stage.value;if(!next&&!['Joined','Not proceeding'].includes(stage)){ $('#activity-status').textContent='Choose the next follow-up date and time above.';return}const value={p_lead_id:id,p_type:f.get('type'),p_outcome:f.get('outcome').trim(),p_note:f.get('note').trim(),p_stage:stage,p_next:next?new Date(next+'+05:30').toISOString():null,p_action:leadForm.elements.next_action.value};const button=event.currentTarget.querySelector('button');button.disabled=true;try{if(demo){demoActivities.unshift({lead_id:id,activity_type:value.p_type,outcome:value.p_outcome,note:value.p_note,created_at:new Date().toISOString()});leads=leads.map(l=>l.id===id?{...l,stage,next_follow_up_at:value.p_next,follow_up:next.slice(0,10),next_action:value.p_action}:l);render()}else{await request('/rest/v1/rpc/log_lead_activity',{method:'POST',body:JSON.stringify(value)});await load()}event.target.reset();await loadActivities(id);$('#activity-status').textContent='Conversation saved and follow-up updated.'}catch(e){$('#activity-status').textContent=e.message}finally{button.disabled=false}});
$('#export').addEventListener('click',()=>{const columns=['name','phone','company','category','email','stage','payment_status','owner','next_follow_up_at','next_action','source'];const safe=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const query=$('#search').value.toLowerCase();const rows=leads.filter(queueMatches).filter(l=>(!$('#stage-filter').value||l.stage===$('#stage-filter').value)&&[l.name,l.company,l.category,l.phone].some(v=>(v||'').toLowerCase().includes(query)));const data=[columns,...rows.map(l=>columns.map(k=>l[k]))].map(r=>r.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nia-leads-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});

function renderCampaignStats(){const groups=new Map();for(const l of leads){const key=l.attribution?.utm_campaign||l.source||'Unspecified';const value=groups.get(key)||{total:0,paid:0,joined:0};value.total++;value.paid+=l.payment_status==='paid'?1:0;value.joined+=l.stage==='Joined'?1:0;groups.set(key,value)}const root=$('#campaign-stats');root.replaceChildren();for(const [key,v] of groups){const p=document.createElement('p');p.textContent=key+': '+v.total+' leads · '+v.paid+' paid visitors · '+v.joined+' joined · '+Math.round(100*v.paid/v.total)+'% paid conversion';root.append(p)}}
