'use strict';
const stages=['New enquiry','Contacted','Qualified','Paid visitor','Attended','Membership discussion','Joined','Not proceeding'];
const $=s=>document.querySelector(s);let leads=[],token=null,demo=false,editing=null;let activityRecords=[];
const config=window.NIA_CONFIG||{};const configured=Boolean(config.supabaseUrl&&config.publishableKey);
for(const s of stages)for(const target of ['#stage-filter','[name=stage]']){const o=document.createElement('option');o.value=o.textContent=s;$(target).append(o)}
function status(message){$('#status').textContent=message}
async function request(path,options={}){const response=await fetch(config.supabaseUrl+path,{...options,headers:{apikey:config.publishableKey,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...options.headers}});const text=await response.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('Unexpected server response. Please retry.')}if(!response.ok){if(response.status===401){token=null;$('#workspace').hidden=true;$('#login').hidden=false;}throw Error(data?.msg||data?.message||data?.error_description||data?.error||'Request failed.')}return data}
function cell(row,text){const td=document.createElement('td');td.textContent=text??'—';row.append(td);return td}
function render(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});const metrics=[['Total leads',leads.length],['Paid visitors',leads.filter(l=>l.payment_status==='paid').length],['Follow-ups due',leads.filter(l=>l.follow_up&&l.follow_up<=today&&!['Joined','Not proceeding'].includes(l.stage)).length],['Attended',leads.filter(l=>['Attended','Membership discussion','Joined'].includes(l.stage)).length]];$('#metrics').replaceChildren();for(const [label,value] of metrics){const box=document.createElement('div');box.className='metric';const b=document.createElement('strong');b.textContent=value;const s=document.createElement('span');s.textContent=label;box.append(b,s);$('#metrics').append(box)}renderCampaignStats();const query=$('#search').value.toLowerCase(),stage=$('#stage-filter').value;const filtered=leads.filter(l=>uiLeadMatches(l)&&queueMatches(l)&&(!stage||l.stage===stage)&&[l.name,l.company,l.category,l.phone].some(v=>(v||'').toLowerCase().includes(query)));filtered.sort(uiLeadSort);$('#rows').replaceChildren();for(const lead of filtered){const row=document.createElement('tr'),td=cell(row,'');const b=document.createElement('strong');b.textContent=lead.name;const small=document.createElement('small');small.textContent=lead.company;td.append(b,small);cell(row,lead.category);cell(row,lead.stage).className='tag-cell';cell(row,lead.payment_status);const due=cell(row,lead.next_follow_up_at?indiaTime(lead.next_follow_up_at):lead.follow_up);if(lead.follow_up&&lead.follow_up<today)due.className='overdue';cell(row,lead.owner);const action=cell(row,'');const button=document.createElement('button');button.textContent='Open';button.addEventListener('click',()=>edit(lead));action.append(button);$('#rows').append(row)}$('#empty').hidden=filtered.length>0}
function openWorkspace(){ $('#login').hidden=true;$('#workspace').hidden=false;$('#signout').hidden=false;$('#mode').textContent=demo?'Sample mode · Not saved':'Staff workspace';render()}
async function load(){if(demo){render();return}status('Loading lead records…');try{leads=await request('/rest/v1/leads?select=*&order=created_at.desc');openWorkspace();status('Lead records loaded. Payment status reflects verified backend records.')}catch(e){status(e.message)}}
let loginEmail='';
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();if(!configured){status('Supabase setup is pending. Staff login is not enabled yet.');return}loginEmail=new FormData(event.currentTarget).get('email').trim();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await request('/auth/v1/otp?redirect_to='+encodeURIComponent(new URL('crm.html',location.href).href),{method:'POST',body:JSON.stringify({email:loginEmail,create_user:false})});status('Check your staff email and open the sign-in link. Only authorised staff can access leads.')}catch(e){status(e.message)}finally{button.disabled=false}});
$('#demo').addEventListener('click',()=>{demo=true;token=null;leads=[{id:'sample-1',name:'Sample Visitor One',company:'Example Design Studio',category:'Architecture',phone:'',email:'',stage:'New enquiry',payment_status:'unpaid',source:'Meta campaign',notes:'Fictional sample. Interested in meeting business owners.',owner:'',follow_up:''},{id:'sample-2',name:'Sample Visitor Two',company:'Example IT Services',category:'IT services',phone:'',email:'',stage:'Paid visitor',payment_status:'paid',source:'Referral',notes:'Fictional sample showing a verified payment status.',owner:'Sample team',follow_up:''}];status('Sample mode: fictional records only. Changes disappear when you leave or reload. Real visitor details must wait for secure setup.');openWorkspace()});
$('#signout').addEventListener('click',async()=>{if(token)try{await request('/auth/v1/logout',{method:'POST'})}catch{}token=null;demo=false;leads=[];$('#workspace').hidden=true;$('#login').hidden=false;$('#signout').hidden=true;$('#mode').textContent=configured?'Staff sign-in':'Setup pending';status('Signed out.');});
function edit(lead){editing=lead?.id||null;const form=$('#edit-form');form.reset();$('#edit-status').textContent='';$('#editor-title').textContent=editing?'Lead details':'Add a lead';for(const key of ['name','phone','company','category','email','stage','owner','next_follow_up_at','next_action','source','notes','payment_status'])form.elements[key].value=(key==='next_follow_up_at'?localTime(lead?.next_follow_up_at):lead?.[key])||({'stage':stages[0],source:'Manual',next_action:'Call',payment_status:'unpaid'}[key]||'');const phone=(lead?.phone||'').replace(/\D/g,'');$('#whatsapp').hidden=demo||!phone;$('#whatsapp').href='https://wa.me/'+(phone.length===10?'91'+phone:phone);$('#activity-section').hidden=!editing;$('#activity-status').textContent='';$('#activity-form').reset();$('#lead-context').textContent=lead?.attribution?.years_in_business?lead.attribution.years_in_business+' years in business · Campaign: '+(lead.attribution.utm_campaign||'direct'):'';$('#editor').showModal();if(editing)loadActivities(editing)}
$('#add').addEventListener('click',()=>edit(null));$('#close').addEventListener('click',()=>$('#editor').close());$('#search').addEventListener('input',()=>render());$('#stage-filter').addEventListener('change',()=>render());$('#refresh').addEventListener('click',load);
$('#edit-form').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);const value=Object.fromEntries(['name','phone','company','category','email','stage','owner','source','notes','next_action'].map(k=>[k,f.get(k).trim()]));value.next_follow_up_at=f.get('next_follow_up_at')?new Date(f.get('next_follow_up_at')+'+05:30').toISOString():null;value.follow_up=value.next_follow_up_at?localTime(value.next_follow_up_at).slice(0,10):null;const button=event.currentTarget.querySelector('button.primary');button.disabled=true;try{if(demo){if(editing)leads=leads.map(l=>l.id===editing?{...l,...value}:l);else leads.unshift({...value,id:crypto.randomUUID(),payment_status:'unpaid'});render()}else{await request('/rest/v1/leads'+(editing?'?id=eq.'+encodeURIComponent(editing):''),{method:editing?'PATCH':'POST',body:JSON.stringify(value),headers:{Prefer:'return=minimal'}});await load()}$('#editor').close()}catch(e){$('#edit-status').textContent=e.message}finally{button.disabled=false}});

(async()=>{const hash=new URLSearchParams(location.hash.slice(1));const incoming=hash.get('access_token');if(!incoming)return;history.replaceState(null,'',location.pathname+location.search);token=incoming;try{const staff=await request('/rest/v1/crm_staff?select=user_id');if(!staff.length){token=null;throw Error('This account is not authorised for the NIA CRM.')}demo=false;await load()}catch(e){token=null;status(e.message)}})();

if(configured){$('#mode').textContent='Staff sign-in';status('Sign in with your authorised staff email to access visitor records.')}

function indiaTime(value){return new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST'}
function localTime(value){if(!value)return '';return new Date(new Date(value).getTime()+19800000).toISOString().slice(0,16)}
function queueMatches(l){const queue=$('#queue-filter').value;if(!queue)return true;if(['Joined','Not proceeding'].includes(l.stage))return false;const next=l.next_follow_up_at;const today=localTime(new Date().toISOString()).slice(0,10);const date=next?localTime(next).slice(0,10):l.follow_up;if(queue==='unscheduled')return !date;if(!date)return false;if(queue==='today')return date===today;if(queue==='overdue')return date<today||(next&&new Date(next)<new Date());return date>today}
$('#queue-filter').addEventListener('change',()=>render());
function renderActivities(){const list=$('#activity-list');list.replaceChildren();if(!activityRecords.length){list.textContent='No conversations logged yet.';return}for(const a of activityRecords){const box=document.createElement('article');box.className='activity';const title=document.createElement('strong');title.textContent=a.activity_type+' · '+a.outcome;const time=document.createElement('small');time.textContent=indiaTime(a.created_at);const note=document.createElement('p');note.textContent=a.note;box.append(title,time,note);list.append(box)}}
async function loadActivities(id){$('#activity-list').textContent='Loading conversation history…';try{activityRecords=demo?demoActivities.filter(a=>a.lead_id===id):await request('/rest/v1/lead_activities?select=*&lead_id=eq.'+encodeURIComponent(id)+'&order=created_at.desc');if(editing===id)renderActivities()}catch(e){$('#activity-list').textContent=e.message}}
let demoActivities=[];
$('#activity-form').addEventListener('submit',async event=>{event.preventDefault();const id=editing;if(!id)return;const f=new FormData(event.currentTarget),leadForm=$('#edit-form');const next=leadForm.elements.next_follow_up_at.value;const stage=leadForm.elements.stage.value;if(!next&&!['Joined','Not proceeding'].includes(stage)){ $('#activity-status').textContent='Choose the next follow-up date and time above.';return}const value={p_lead_id:id,p_type:f.get('type'),p_outcome:f.get('outcome').trim(),p_note:f.get('note').trim(),p_stage:stage,p_next:next?new Date(next+'+05:30').toISOString():null,p_action:leadForm.elements.next_action.value};const button=event.currentTarget.querySelector('button');button.disabled=true;try{if(demo){demoActivities.unshift({lead_id:id,activity_type:value.p_type,outcome:value.p_outcome,note:value.p_note,created_at:new Date().toISOString()});leads=leads.map(l=>l.id===id?{...l,stage,next_follow_up_at:value.p_next,follow_up:next.slice(0,10),next_action:value.p_action}:l);render()}else{await request('/rest/v1/rpc/log_lead_activity',{method:'POST',body:JSON.stringify(value)});await load()}event.target.reset();await loadActivities(id);$('#activity-status').textContent='Conversation saved and follow-up updated.'}catch(e){$('#activity-status').textContent=e.message}finally{button.disabled=false}});
$('#export').addEventListener('click',()=>{const columns=['name','phone','company','category','email','stage','payment_status','owner','next_follow_up_at','next_action','source'];const safe=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const query=$('#search').value.toLowerCase();const rows=leads.filter(uiLeadMatches).filter(queueMatches).filter(l=>(!$('#stage-filter').value||l.stage===$('#stage-filter').value)&&[l.name,l.company,l.category,l.phone].some(v=>(v||'').toLowerCase().includes(query)));const data=[columns,...rows.map(l=>columns.map(k=>l[k]))].map(r=>r.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nia-leads-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});

function renderCampaignStats(){const groups=new Map();for(const l of leads){const key=l.attribution?.utm_campaign||l.source||'Unspecified';const value=groups.get(key)||{total:0,paid:0,joined:0};value.total++;value.paid+=l.payment_status==='paid'?1:0;value.joined+=l.stage==='Joined'?1:0;groups.set(key,value)}const root=$('#campaign-stats');root.replaceChildren();for(const [key,v] of groups){const p=document.createElement('p');p.textContent=key+': '+v.total+' leads · '+v.paid+' paid visitors · '+v.joined+' joined · '+Math.round(100*v.paid/v.total)+'% paid conversion';root.append(p)}}

$('#wa-refresh').addEventListener('click',async()=>{
 const root=$('#wa-events');root.replaceChildren();
 if(demo){$('#wa-status').textContent='Sample mode: WhatsApp is disconnected. No messages are sent.';return;}
 const button=$('#wa-refresh');button.disabled=true;
 try{
  const events=await request('/rest/v1/wa_events?select=kind,contact_id,event_at,body,status&order=event_at.desc&limit=100');
  $('#wa-status').textContent=events.length?'Latest 100 events from the broadcast number.':'No WhatsApp events recorded yet.';
  for(const e of events){const box=document.createElement('article');box.className='activity';const title=document.createElement('strong');title.textContent=e.contact_id+' · '+(e.kind==='incoming'?'Incoming reply':e.status);const time=document.createElement('small');time.textContent=indiaTime(e.event_at);const body=document.createElement('p');body.textContent=e.body;box.append(title,time,body);root.append(box);}
 }catch{$('#wa-status').textContent='WhatsApp storage is not connected yet. Complete the backend setup first.';}
 finally{button.disabled=false;}
});

let waReplyAttempt=null;
$('#wa-reply-form').addEventListener('submit',async event=>{
 event.preventDefault();const status=$('#wa-reply-status');
 if(demo){status.textContent='Sample mode cannot send WhatsApp messages.';return;}
 const f=new FormData(event.currentTarget);const body=f.get('body').trim(),contact_id=f.get('contact_id').trim();
 if(!waReplyAttempt||waReplyAttempt.body!==body||waReplyAttempt.contact_id!==contact_id)waReplyAttempt={request_id:crypto.randomUUID(),body,contact_id};
 const button=event.currentTarget.querySelector('button');button.disabled=true;
 try{const result=await request('/functions/v1/whatsapp-reply',{method:'POST',body:JSON.stringify(waReplyAttempt)});status.textContent=result.state==='accepted'?'Meta accepted the reply. Check delivery updates.':'Send state: '+result.state+'. Refresh before trying again.';}
 catch(e){status.textContent=e.message;}
 finally{button.disabled=false;}
});

const waNumber=p=>{const n=(p||'').replace(/\D/g,'');return n.length===10?'91'+n:n;};
$('#wa-consent-form').addEventListener('submit',async e=>{
 e.preventDefault();if(demo){$('#wa-status').textContent='Sample mode cannot save permissions.';return;}
 const f=new FormData(e.currentTarget);
 try{await request('/rest/v1/rpc/wa_record_consent',{method:'POST',body:JSON.stringify({p_contact:f.get('contact'),p_opted_in:f.get('permission')==='true',p_evidence:f.get('evidence')})});$('#wa-status').textContent='Marketing permission saved.';}catch(err){$('#wa-status').textContent=err.message;}
});
$('#wa-campaign-form').addEventListener('submit',async e=>{
 e.preventDefault();if(demo){$('#wa-status').textContent='Sample mode cannot create campaigns.';return;}if(!selectedTemplate){$('#wa-status').textContent='Choose one approved template first.';return;}
 const q=$('#search').value.toLowerCase();const contacts=[...new Set(leads.filter(l=>uiLeadMatches(l)&&queueMatches(l)&&(!$('#stage-filter').value||l.stage===$('#stage-filter').value)&&[l.name,l.company,l.category,l.phone].some(v=>(v||'').toLowerCase().includes(q))).map(l=>waNumber(l.phone)).filter(n=>/^[0-9]{8,15}$/.test(n)))];
 const chosenContacts=$('#wa-recipient-source').value==='contacts'?[...selectedContacts]:contacts;
 const button=$('#wa-save-campaign')||e.currentTarget.querySelector('button');button.disabled=true;
 try{await request('/rest/v1/rpc/wa_create_template_campaign',{method:'POST',body:JSON.stringify({p_name:new FormData(e.currentTarget).get('name'),p_contacts:chosenContacts,p_template:selectedTemplate?.id})});$('#wa-status').textContent='Draft created. Review recipients before launching.';await loadWaCampaigns();}catch(err){$('#wa-status').textContent=err.message;}finally{button.disabled=false;}
});
async function loadWaCampaigns(){
 const root=$('#wa-campaigns');root.replaceChildren();if(demo)return;
 try{const campaigns=await request('/rest/v1/wa_campaigns?select=*&order=created_at.desc&limit=20');
 for(const c of campaigns){const recipients=await request('/rest/v1/wa_campaign_recipients?campaign_id=eq.'+c.id+'&select=contact_id,recipient_name,state,message_id,error_code');
 const box=document.createElement('article');box.className='activity';const title=document.createElement('strong');title.textContent=c.name+' · '+c.template+' / '+c.language+' · '+c.state+' · '+recipients.length+' recipients';box.append(title);
 const list=document.createElement('p');list.textContent=recipients.map(r=>r.recipient_name+' ('+r.contact_id+') — '+r.state+(r.error_code?' / Meta '+r.error_code:'')).join('\n');list.style.whiteSpace='pre-wrap';box.append(list);
 if(c.state==='draft'||recipients.some(r=>r.state==='pending')){const b=document.createElement('button');b.textContent=c.state==='draft'?'Launch reviewed campaign':'Process next 5 recipients';b.addEventListener('click',async()=>{
 if(c.state==='draft'&&!confirm('Send '+c.template+' from 7997994495 to the '+recipients.length+' recipients shown?'))return;
 b.disabled=true;try{if(c.state==='draft')await request('/rest/v1/rpc/wa_launch_campaign',{method:'POST',body:JSON.stringify({p_id:c.id})});const result=await request('/functions/v1/whatsapp-campaign',{method:'POST',body:JSON.stringify({campaign_id:c.id})});$('#wa-status').textContent=result.processed+' recipients processed. Accepted messages are not confirmed delivered.';await loadWaCampaigns();}catch(err){$('#wa-status').textContent=err.message;b.disabled=false;}
 });box.append(b);}root.append(box);}
 }catch(err){$('#wa-status').textContent=err.message;}
}
$('#wa-campaign-refresh').addEventListener('click',loadWaCampaigns);

let selectedTemplate=null,templateRows=[];
function templateText(components){return (components||[]).map(c=>c.text||c.buttons?.map(b=>b.text+' → '+b.url).join('\n')||'').filter(Boolean).join('\n\n').replaceAll('{{1}}','Visitor');}
async function loadTemplates(){
 const body=$('#wa-template-rows');body.replaceChildren();
 try{templateRows=demo?[{id:'demo-approved',name:'sample_invitation',language:'en_US',category:'MARKETING',status:'APPROVED',supported:true,components:[{type:'BODY',text:'Hello {{1}}, this is a fictional preview.'}]},{id:'demo-pending',name:'sample_pending',language:'en_US',category:'MARKETING',status:'PENDING',supported:true,components:[]}]:await request('/rest/v1/wa_templates?select=*&order=updated_at.desc');
 if(selectedTemplate){selectedTemplate=templateRows.find(t=>t.id===selectedTemplate.id&&t.status==='APPROVED'&&t.supported)||null;}
 if(!selectedTemplate)$('#wa-selected-preview').textContent='';
 $('#wa-template-selection').textContent=selectedTemplate?'Selected: '+selectedTemplate.name+' · '+selectedTemplate.language:'Choose one approved template from the table.';
 for(const t of templateRows){const tr=document.createElement('tr'),td=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label','Choose '+t.name+' '+t.language);check.checked=selectedTemplate?.id===t.id;check.disabled=t.status!=='APPROVED'||!t.supported;check.addEventListener('change',()=>{selectedTemplate=check.checked?t:null;$('#wa-selected-preview').textContent=selectedTemplate?templateText(t.components):'';loadTemplates();});td.append(check);tr.append(td);cell(tr,t.name);cell(tr,t.language);cell(tr,t.category);cell(tr,t.status+(t.status==='APPROVED'&&!t.supported?' · not supported by this sender':''));const action=cell(tr,'');const preview=document.createElement('button');preview.type='button';preview.textContent='Preview';preview.addEventListener('click',()=>$('#wa-selected-preview').textContent=templateText(t.components));action.append(preview);
 if(t.components?.some(c=>c.type==='HEADER'&&['IMAGE','VIDEO','DOCUMENT'].includes(c.format))){const a=document.createElement('button');a.type='button';a.textContent='Attach media';a.disabled=demo;a.addEventListener('click',async()=>{a.disabled=true;try{const m=await uploadTemplateMedia(true);await request('/functions/v1/whatsapp-templates',{method:'POST',body:JSON.stringify({action:'attach',id:t.id,...m})});$('#wa-template-status').textContent='Send media attached.';await loadTemplates();}catch(e){$('#wa-template-status').textContent=e.message;}finally{a.disabled=false;}});action.append(a);}
 if(t.status==='DRAFT'){const b=document.createElement('button');b.type='button';b.textContent='Submit to Meta';b.disabled=demo;b.addEventListener('click',async()=>{if(!confirm('Submit '+t.name+' to Meta for marketing template approval?'))return;b.disabled=true;try{const result=await request('/functions/v1/whatsapp-templates',{method:'POST',body:JSON.stringify({action:'submit',id:t.id})});$('#wa-template-status').textContent='Meta status: '+result.status;await loadTemplates();}catch(e){$('#wa-template-status').textContent=e.message;await loadTemplates();}});action.append(b);}body.append(tr);}
 if(!templateRows.length)$('#wa-template-status').textContent='No templates saved yet. Sync Meta or create a draft.';
 }catch(e){$('#wa-template-status').textContent=e.message;}
}
$('#wa-template-sync').addEventListener('click',async e=>{if(demo){$('#wa-template-status').textContent='Sample mode uses fictional templates.';await loadTemplates();return;}e.currentTarget.disabled=true;try{const result=await request('/functions/v1/whatsapp-templates',{method:'POST',body:JSON.stringify({action:'sync'})});$('#wa-template-status').textContent=result.count+' Meta templates synced just now.';await loadTemplates();}catch(e){$('#wa-template-status').textContent=e.message;}finally{$('#wa-template-sync').disabled=false;}});
$('#wa-template-form').addEventListener('submit',async e=>{e.preventDefault();if(demo){$('#wa-template-status').textContent='Sample mode cannot save or submit templates.';return;}const b=e.currentTarget.querySelector('button:last-child');b.disabled=true;try{await request('/functions/v1/whatsapp-templates',{method:'POST',body:JSON.stringify({action:'draft',...Object.fromEntries(new FormData(e.currentTarget)),...await uploadTemplateMedia()})});$('#wa-template-status').textContent='Draft saved. Preview it in the table before submitting to Meta.';await loadTemplates();}catch(e){$('#wa-template-status').textContent=e.message;}finally{b.disabled=false;}});
$('#wa-template-preview-button').addEventListener('click',()=>{const f=new FormData($('#wa-template-form'));$('#wa-template-preview').textContent=[f.get('header'),f.get('body'),f.get('footer'),f.get('url')?f.get('button')+' → '+f.get('url'):''].filter(Boolean).join('\n\n').replaceAll('{{1}}','Visitor');});
$('#workspace details.campaign-summary').addEventListener('toggle',e=>{if(e.currentTarget.open&&(token||demo))loadTemplates();});

let selectedContacts=new Set(),importRows=[];
function switchCrmTab(wa){$('#wa-broadcast-panel').hidden=!wa;$('#pipeline-panel').hidden=wa;$('#wa-broadcast-tab').setAttribute('aria-selected',String(wa));$('#pipeline-tab').setAttribute('aria-selected',String(!wa));if(wa){const detail=$('#wa-broadcast-panel details.campaign-summary');detail.open=true;loadTemplates();loadBroadcastContacts();loadWaCampaigns();}}
$('#wa-broadcast-tab').addEventListener('click',()=>switchCrmTab(true));$('#pipeline-tab').addEventListener('click',()=>switchCrmTab(false));
async function uploadTemplateMedia(required=false){
 const kind=$('#wa-media-type').value,file=$('#wa-template-media').files[0];if(kind==='TEXT'&&!required)return {};if(!file)throw Error('Choose a media file first.');if(file.size>5*1024*1024)throw Error('Media must be 5 MB or smaller.');
 const mime={IMAGE:['image/jpeg','image/png'],VIDEO:['video/mp4'],DOCUMENT:['application/pdf']}[kind];if(!mime?.includes(file.type))throw Error('Choose a file matching the header type.');
 const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Cannot read media file'));reader.readAsDataURL(file);});
 $('#wa-template-status').textContent='Uploading media to Meta…';const result=await request('/functions/v1/whatsapp-templates',{method:'POST',body:JSON.stringify({action:'upload',mime:file.type,filename:file.name,data})});return {media_id:result.media.id};
}
async function loadBroadcastContacts(){const root=$('#wa-contact-rows');root.replaceChildren();if(demo){$('#wa-import-status').textContent='Sample mode cannot import real contacts.';return;}
 try{const contacts=[];for(let offset=0;offset<2000;offset+=1000){const page=await request('/rest/v1/wa_contacts?select=*&order=name,contact_id&limit=1000&offset='+offset);contacts.push(...page);if(page.length<1000)break;}const permissions=[];for(let offset=0;offset<10000;offset+=1000){const page=await request('/rest/v1/wa_permissions?select=contact_id,opted_in&order=contact_id&limit=1000&offset='+offset);permissions.push(...page);if(page.length<1000)break;}const allowed=new Set(permissions.filter(p=>p.opted_in).map(p=>p.contact_id));for(const c of contacts){const tr=document.createElement('tr'),td=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label','Choose contact '+c.contact_id);check.checked=selectedContacts.has(c.contact_id);check.disabled=!allowed.has(c.contact_id);if(check.disabled)selectedContacts.delete(c.contact_id);check.addEventListener('change',()=>check.checked?selectedContacts.add(c.contact_id):selectedContacts.delete(c.contact_id));td.append(check);tr.append(td);cell(tr,c.name);cell(tr,c.contact_id);cell(tr,c.company);cell(tr,allowed.has(c.contact_id)?'Opted in':'Not opted in');root.append(tr);}}
 catch(e){$('#wa-import-status').textContent=e.message;}}
$('#wa-contact-refresh').addEventListener('click',loadBroadcastContacts);
$('#wa-import-preview-button').addEventListener('click',async()=>{
 importRows=[];$('#wa-import-save').disabled=true;$('#wa-import-preview').replaceChildren();const file=$('#wa-contact-file').files[0];if(!file){$('#wa-import-status').textContent='Choose a CSV or Excel file.';return;}if(file.size>5*1024*1024){$('#wa-import-status').textContent='Contact file must be 5 MB or smaller.';return;}
 try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',sheetRows:2002}),rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:'',raw:true});if(rows.length>2000)throw Error('Maximum 2,000 contact rows per file.');const norm=k=>k.toLowerCase().replace(/[^a-z]/g,'');let invalid=0,duplicates=0;const seen=new Set();for(const row of rows){const fields=Object.fromEntries(Object.entries(row).map(([k,v])=>[norm(k),v]));const value=fields.phone||fields.mobile||fields.whatsapp||fields.phonenumber||fields.mobilenumber;const raw=String(value||'').trim();const contact_id=waNumber(raw);const name=String(fields.name||fields.fullname||fields.contactname||'').trim(),company=String(fields.company||fields.business||'').trim();if(!name||name.length>200||company.length>200||/[eE][+-]?\d/.test(raw)||!/^\+?[\d\s().-]+$/.test(raw)||!/^\d{8,15}$/.test(contact_id)){invalid++;continue;}if(seen.has(contact_id)){duplicates++;continue;}seen.add(contact_id);importRows.push({contact_id,name,company});}
 for(const c of importRows.slice(0,20)){const tr=document.createElement('tr');cell(tr,c.name);cell(tr,c.contact_id);cell(tr,c.company);$('#wa-import-preview').append(tr);}
 $('#wa-import-status').textContent=importRows.length+' valid contacts · '+invalid+' invalid rows · '+duplicates+' duplicate numbers. Preview shows first 20. No marketing consent imported.';$('#wa-import-save').disabled=demo||!importRows.length;
 }catch(e){$('#wa-import-status').textContent=e.message;}
});
$('#wa-import-form').addEventListener('submit',async e=>{e.preventDefault();if(demo||!importRows.length)return;$('#wa-import-save').disabled=true;let count=0;try{for(let i=0;i<importRows.length;i+=100){count+=await request('/rest/v1/rpc/wa_import_contacts',{method:'POST',body:JSON.stringify({p_rows:importRows.slice(i,i+100)})});$('#wa-import-status').textContent=count+' contacts imported…';}$('#wa-import-status').textContent=count+' contacts imported. Record consent before campaign selection.';importRows=[];await loadBroadcastContacts();}catch(e){$('#wa-import-status').textContent=count+' saved before error: '+e.message;$('#wa-import-save').disabled=false;}});

function uiLeadMatches(l){return (!$('#owner-filter')?.value||l.owner===$('#owner-filter').value)&&(!$('#source-filter')?.value||l.source===$('#source-filter').value);}
function uiLeadSort(a,b){const mode=$('#lead-sort')?.value;if(mode==='name')return (a.name||'').localeCompare(b.name||'');if(mode==='stage')return stages.indexOf(a.stage)-stages.indexOf(b.stage);if(mode==='followup')return (a.next_follow_up_at||a.follow_up||'9999').localeCompare(b.next_follow_up_at||b.follow_up||'9999');return (b.created_at||'').localeCompare(a.created_at||'');}
